import type { Listing } from "./types";

/**
 * Real diamond listings sourced from UK retailers (March 2026).
 * Prices from Blue Nile and James Allen converted from USD at ~0.79.
 * Used as fallback when Supabase is not configured.
 */
export const sampleListings: Listing[] = [
  // ── Blue Nile UK: 1.0ct cluster, H colour, VS1-VS2 ──
  { id: "bn-1", carat: 1.00, cut: "Very Good", color: "H", clarity: "VS1", price_gbp: 2094, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/26311555", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-2", carat: 1.02, cut: "Very Good", color: "G", clarity: "VS2", price_gbp: 2188, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/25805279", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-3", carat: 1.02, cut: "Very Good", color: "H", clarity: "VS1", price_gbp: 2228, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/26385845", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-4", carat: 1.00, cut: "Very Good", color: "G", clarity: "VS2", price_gbp: 2244, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/27767361", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-5", carat: 1.00, cut: "Very Good", color: "H", clarity: "VS2", price_gbp: 2259, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/27933362", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-6", carat: 1.01, cut: "Very Good", color: "H", clarity: "VS2", price_gbp: 2267, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/28480394", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-7", carat: 1.00, cut: "Very Good", color: "H", clarity: "VS1", price_gbp: 2283, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/28561350", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-8", carat: 1.01, cut: "Excellent", color: "H", clarity: "VS2", price_gbp: 2283, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/28553155", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-9", carat: 1.00, cut: "Excellent", color: "H", clarity: "VS2", price_gbp: 2291, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/27863288", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-10", carat: 1.00, cut: "Very Good", color: "H", clarity: "VS1", price_gbp: 2291, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/28477021", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "bn-11", carat: 1.00, cut: "Excellent", color: "H", clarity: "VS2", price_gbp: 2299, retailer_name: "Blue Nile", certification_body: "GIA", retailer_url: "https://www.bluenile.com/uk/diamond-details/26178111", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },

  // ── James Allen: 1.0ct cluster, various colours, SI1 clarity ──
  { id: "ja-1", carat: 1.00, cut: "Excellent", color: "G", clarity: "SI1", price_gbp: 1177, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-g-color-si1-clarity-excellent-cut-sku-28427150", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-2", carat: 1.00, cut: "Excellent", color: "F", clarity: "SI1", price_gbp: 1272, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-f-color-si1-clarity-excellent-cut-sku-28446726", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-3", carat: 1.00, cut: "Excellent", color: "F", clarity: "SI1", price_gbp: 1454, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-f-color-si1-clarity-excellent-cut-sku-28479062", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-4", carat: 1.00, cut: "Excellent", color: "E", clarity: "SI1", price_gbp: 1525, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-e-color-si1-clarity-excellent-cut-sku-27624817", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-5", carat: 1.00, cut: "Excellent", color: "G", clarity: "SI1", price_gbp: 1564, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-g-color-si1-clarity-excellent-cut-sku-26332289", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-6", carat: 1.00, cut: "Very Good", color: "F", clarity: "SI1", price_gbp: 1564, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-f-color-si1-clarity-very-good-cut-sku-28284317", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-7", carat: 1.00, cut: "Excellent", color: "H", clarity: "SI1", price_gbp: 1588, retailer_name: "James Allen", certification_body: "GIA", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-h-color-si1-clarity-excellent-cut-sku-28427875", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-8", carat: 1.00, cut: "Very Good", color: "G", clarity: "SI1", price_gbp: 1604, retailer_name: "James Allen", certification_body: "GIA", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-g-color-si1-clarity-very-good-cut-sku-27767278", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },

  // ── James Allen: 0.70ct cluster ──
  { id: "ja-9", carat: 0.70, cut: "Excellent", color: "G", clarity: "SI1", price_gbp: 600, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/0.70-carat-g-color-si1-clarity-excellent-cut-sku-27073256", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-10", carat: 0.70, cut: "Excellent", color: "H", clarity: "SI1", price_gbp: 624, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/0.70-carat-h-color-si1-clarity-excellent-cut-sku-27043777", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-11", carat: 0.70, cut: "Very Good", color: "E", clarity: "SI1", price_gbp: 632, retailer_name: "James Allen", certification_body: "GIA", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/0.70-carat-e-color-si1-clarity-very-good-cut-sku-27531011", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-12", carat: 0.74, cut: "Excellent", color: "G", clarity: "SI1", price_gbp: 640, retailer_name: "James Allen", certification_body: "IGI", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/0.74-carat-g-color-si1-clarity-excellent-cut-sku-26380912", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "ja-13", carat: 0.70, cut: "Very Good", color: "H", clarity: "SI1", price_gbp: 640, retailer_name: "James Allen", certification_body: "GIA", retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/0.70-carat-h-color-si1-clarity-very-good-cut-sku-27547060", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },

  // ── 77 Diamonds: links to search page (individual listings are JS-rendered) ──
  { id: "77-1", carat: 1.00, cut: "Excellent", color: "G", clarity: "VS1", price_gbp: 2350, retailer_name: "77 Diamonds", certification_body: "GIA", retailer_url: "https://www.77diamonds.com/round-cut-diamonds", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "77-2", carat: 1.01, cut: "Very Good", color: "H", clarity: "VS2", price_gbp: 1890, retailer_name: "77 Diamonds", certification_body: "IGI", retailer_url: "https://www.77diamonds.com/round-cut-diamonds", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "77-3", carat: 0.70, cut: "Excellent", color: "F", clarity: "VS1", price_gbp: 980, retailer_name: "77 Diamonds", certification_body: "GIA", retailer_url: "https://www.77diamonds.com/round-cut-diamonds", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "77-4", carat: 1.00, cut: "Good", color: "G", clarity: "VS1", price_gbp: 1750, retailer_name: "77 Diamonds", certification_body: "IGI", retailer_url: "https://www.77diamonds.com/round-cut-diamonds", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },

  // ── Queensmith: links to loose diamonds page (JS-rendered inventory) ──
  { id: "qs-1", carat: 1.00, cut: "Excellent", color: "G", clarity: "VS1", price_gbp: 2500, retailer_name: "Queensmith", certification_body: "GIA", retailer_url: "https://www.queensmith.co.uk/diamonds/loose-diamonds", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "qs-2", carat: 1.00, cut: "Very Good", color: "H", clarity: "VS2", price_gbp: 2100, retailer_name: "Queensmith", certification_body: "GIA", retailer_url: "https://www.queensmith.co.uk/diamonds/loose-diamonds", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
  { id: "qs-3", carat: 0.75, cut: "Excellent", color: "F", clarity: "VVS2", price_gbp: 1650, retailer_name: "Queensmith", certification_body: "GIA", retailer_url: "https://www.queensmith.co.uk/diamonds/loose-diamonds", shape: "Round", diamond_type: "natural", symmetry: null, polish: null, fluorescence: null, created_at: "2026-03-28" },
];
