import type { Listing } from "./types";

/**
 * Sample diamond listings with a realistic mix of natural and lab-grown stones.
 * Natural: GBP 800-5,000 | Lab-grown: GBP 200-1,500 (~73% cheaper for equiv specs).
 * Used as fallback when Supabase is not configured.
 */
export const sampleListings: Listing[] = [
  // ── Blue Nile – Natural (GIA certified) ──────────────────────────────────
  {
    id: "bn-1",
    carat: 1.00, cut: "Excellent", color: "G", clarity: "VS1",
    price_gbp: 3150,
    retailer_name: "Blue Nile", certification_body: "GIA",
    retailer_url: "https://www.bluenile.com/uk/diamond-details/26311555",
    shape: "Round", diamond_type: "natural",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },
  {
    id: "bn-2",
    carat: 1.02, cut: "Very Good", color: "H", clarity: "VS2",
    price_gbp: 2188,
    retailer_name: "Blue Nile", certification_body: "GIA",
    retailer_url: "https://www.bluenile.com/uk/diamond-details/25805279",
    shape: "Round", diamond_type: "natural",
    symmetry: "Very Good", polish: "Very Good", fluorescence: "Faint",
    created_at: "2026-03-28",
  },
  {
    id: "bn-3",
    carat: 0.70, cut: "Very Good", color: "H", clarity: "VS1",
    price_gbp: 1050,
    retailer_name: "Blue Nile", certification_body: "GIA",
    retailer_url: "https://www.bluenile.com/uk/diamond-details/26385845",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "bn-4",
    carat: 1.50, cut: "Excellent", color: "F", clarity: "VS2",
    price_gbp: 4800,
    retailer_name: "Blue Nile", certification_body: "GIA",
    retailer_url: "https://www.bluenile.com/uk/diamond-details/27767361",
    shape: "Round", diamond_type: "natural",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },
  {
    id: "bn-5",
    carat: 0.90, cut: "Good", color: "J", clarity: "SI2",
    price_gbp: 870,
    retailer_name: "Blue Nile", certification_body: "HRD",
    retailer_url: "https://www.bluenile.com/uk/diamond-details/27933362",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },

  // ── Blue Nile – Lab-grown (IGI certified) ────────────────────────────────
  {
    id: "bn-lab-1",
    carat: 1.00, cut: "Excellent", color: "G", clarity: "VS1",
    price_gbp: 720,
    retailer_name: "Blue Nile", certification_body: "IGI",
    retailer_url: "https://www.bluenile.com/uk/lab-grown-diamonds/26311556",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },
  {
    id: "bn-lab-2",
    carat: 1.50, cut: "Excellent", color: "F", clarity: "VS2",
    price_gbp: 1100,
    retailer_name: "Blue Nile", certification_body: "IGI",
    retailer_url: "https://www.bluenile.com/uk/lab-grown-diamonds/27767362",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "bn-lab-3",
    carat: 2.00, cut: "Excellent", color: "E", clarity: "VVS2",
    price_gbp: 1490,
    retailer_name: "Blue Nile", certification_body: "IGI",
    retailer_url: "https://www.bluenile.com/uk/lab-grown-diamonds/28100001",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },

  // ── James Allen – Natural (GIA / IGI / AGS mix) ──────────────────────────
  {
    id: "ja-1",
    carat: 1.00, cut: "Excellent", color: "G", clarity: "SI1",
    price_gbp: 2050,
    retailer_name: "James Allen", certification_body: "GIA",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.00-carat-g-color-si1-clarity-sku-28427150",
    shape: "Round", diamond_type: "natural",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },
  {
    id: "ja-2",
    carat: 0.75, cut: "Excellent", color: "F", clarity: "VS1",
    price_gbp: 1420,
    retailer_name: "James Allen", certification_body: "GIA",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/0.75-carat-f-color-vs1-clarity-sku-28446726",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "ja-3",
    carat: 1.25, cut: "Very Good", color: "H", clarity: "VS2",
    price_gbp: 2880,
    retailer_name: "James Allen", certification_body: "AGS",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/1.25-carat-h-color-vs2-clarity-sku-28479062",
    shape: "Round", diamond_type: "natural",
    symmetry: "Very Good", polish: "Excellent", fluorescence: "Faint",
    created_at: "2026-03-28",
  },
  {
    id: "ja-4",
    carat: 0.60, cut: "Good", color: "I", clarity: "SI1",
    price_gbp: 820,
    retailer_name: "James Allen", certification_body: "IGI",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/0.60-carat-i-color-si1-clarity-sku-27624817",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "ja-5",
    carat: 2.00, cut: "Excellent", color: "D", clarity: "IF",
    price_gbp: 4990,
    retailer_name: "James Allen", certification_body: "GIA",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/round-cut/2.00-carat-d-color-if-clarity-sku-26332289",
    shape: "Round", diamond_type: "natural",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },

  // ── James Allen – Lab-grown (IGI / GCAL / GIA mix) ──────────────────────
  {
    id: "ja-lab-1",
    carat: 1.00, cut: "Excellent", color: "E", clarity: "VS1",
    price_gbp: 590,
    retailer_name: "James Allen", certification_body: "IGI",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/lab-grown/1.00-carat-e-color-vs1-clarity-sku-lab-10001",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "ja-lab-2",
    carat: 1.50, cut: "Excellent", color: "F", clarity: "VVS1",
    price_gbp: 990,
    retailer_name: "James Allen", certification_body: "IGI",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/lab-grown/1.50-carat-f-color-vvs1-clarity-sku-lab-10002",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },
  {
    id: "ja-lab-3",
    carat: 0.75, cut: "Very Good", color: "G", clarity: "VS2",
    price_gbp: 360,
    retailer_name: "James Allen", certification_body: "GCAL",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/lab-grown/0.75-carat-g-color-vs2-clarity-sku-lab-10003",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "ja-lab-4",
    carat: 2.00, cut: "Excellent", color: "D", clarity: "IF",
    price_gbp: 1380,
    retailer_name: "James Allen", certification_body: "GIA",
    retailer_url: "https://www.jamesallen.com/loose-diamonds/lab-grown/2.00-carat-d-color-if-clarity-sku-lab-10004",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },

  // ── 77 Diamonds – Natural (GIA / HRD / AGS mix) ──────────────────────────
  {
    id: "77-1",
    carat: 1.00, cut: "Excellent", color: "G", clarity: "VS1",
    price_gbp: 2650,
    retailer_name: "77 Diamonds", certification_body: "GIA",
    retailer_url: "https://www.77diamonds.com/round-cut-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "77-2",
    carat: 1.20, cut: "Very Good", color: "H", clarity: "VS2",
    price_gbp: 2420,
    retailer_name: "77 Diamonds", certification_body: "HRD",
    retailer_url: "https://www.77diamonds.com/round-cut-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: "Very Good", polish: "Very Good", fluorescence: "Medium",
    created_at: "2026-03-28",
  },
  {
    id: "77-3",
    carat: 0.50, cut: "Excellent", color: "F", clarity: "VVS2",
    price_gbp: 900,
    retailer_name: "77 Diamonds", certification_body: "AGS",
    retailer_url: "https://www.77diamonds.com/round-cut-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "77-4",
    carat: 1.75, cut: "Good", color: "I", clarity: "SI1",
    price_gbp: 3100,
    retailer_name: "77 Diamonds", certification_body: "GIA",
    retailer_url: "https://www.77diamonds.com/round-cut-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },

  // ── 77 Diamonds – Lab-grown (IGI certified) ──────────────────────────────
  {
    id: "77-lab-1",
    carat: 1.00, cut: "Excellent", color: "G", clarity: "VS1",
    price_gbp: 610,
    retailer_name: "77 Diamonds", certification_body: "IGI",
    retailer_url: "https://www.77diamonds.com/lab-grown-diamonds",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "77-lab-2",
    carat: 0.50, cut: "Excellent", color: "E", clarity: "VVS1",
    price_gbp: 210,
    retailer_name: "77 Diamonds", certification_body: "IGI",
    retailer_url: "https://www.77diamonds.com/lab-grown-diamonds",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },

  // ── Queensmith – Natural (GIA certified) ─────────────────────────────────
  {
    id: "qs-1",
    carat: 1.00, cut: "Excellent", color: "G", clarity: "VS1",
    price_gbp: 2850,
    retailer_name: "Queensmith", certification_body: "GIA",
    retailer_url: "https://www.queensmith.co.uk/diamonds/loose-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "None",
    created_at: "2026-03-28",
  },
  {
    id: "qs-2",
    carat: 0.80, cut: "Very Good", color: "H", clarity: "SI1",
    price_gbp: 1240,
    retailer_name: "Queensmith", certification_body: "GIA",
    retailer_url: "https://www.queensmith.co.uk/diamonds/loose-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "qs-3",
    carat: 1.50, cut: "Excellent", color: "E", clarity: "VVS1",
    price_gbp: 4650,
    retailer_name: "Queensmith", certification_body: "GIA",
    retailer_url: "https://www.queensmith.co.uk/diamonds/loose-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: "Excellent", polish: "Excellent", fluorescence: "Faint",
    created_at: "2026-03-28",
  },
  {
    id: "qs-4",
    carat: 0.55, cut: "Good", color: "J", clarity: "SI2",
    price_gbp: 810,
    retailer_name: "Queensmith", certification_body: "GIA",
    retailer_url: "https://www.queensmith.co.uk/diamonds/loose-diamonds",
    shape: "Round", diamond_type: "natural",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },

  // ── Queensmith – Lab-grown (IGI / GCAL) ──────────────────────────────────
  {
    id: "qs-lab-1",
    carat: 1.00, cut: "Excellent", color: "E", clarity: "VS1",
    price_gbp: 620,
    retailer_name: "Queensmith", certification_body: "IGI",
    retailer_url: "https://www.queensmith.co.uk/diamonds/lab-grown",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
  {
    id: "qs-lab-2",
    carat: 1.50, cut: "Very Good", color: "F", clarity: "VS2",
    price_gbp: 880,
    retailer_name: "Queensmith", certification_body: "GCAL",
    retailer_url: "https://www.queensmith.co.uk/diamonds/lab-grown",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: "Very Good", polish: "Very Good", fluorescence: "None",
    created_at: "2026-03-28",
  },
  {
    id: "qs-lab-3",
    carat: 0.70, cut: "Excellent", color: "G", clarity: "VVS2",
    price_gbp: 290,
    retailer_name: "Queensmith", certification_body: "IGI",
    retailer_url: "https://www.queensmith.co.uk/diamonds/lab-grown",
    shape: "Round", diamond_type: "lab-grown",
    symmetry: null, polish: null, fluorescence: null,
    created_at: "2026-03-28",
  },
];
